# SOPS (Secrets Operations) Configuration
# For encrypted secrets management in GitOps
# Following security best practices from GitOps principles

# Example SOPS configuration file
# Place this in your GitOps repository root or secrets directory

creation_rules:
  # Production secrets encrypted with AWS KMS
  - path_regex: secrets/prod/.*\.yaml$
    kms: arn:aws:kms:us-west-2:ACCOUNT_ID:key/KMS_KEY_ID
    aws_profile: default
    encrypted_regex: ^(data|stringData)$

  # Staging secrets encrypted with AWS KMS
  - path_regex: secrets/staging/.*\.yaml$
    kms: arn:aws:kms:us-west-2:ACCOUNT_ID:key/KMS_KEY_ID
    aws_profile: default
    encrypted_regex: ^(data|stringData)$

  # Age encryption for local development
  - path_regex: secrets/dev/.*\.yaml$
    age: >-
      age1xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    encrypted_regex: ^(data|stringData)$
