apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spot-app
  namespace: argocd
spec:
  project: default
  
  source:
    repoURL: https://github.com/seanebones-lang/Spot.git
    targetRevision: main
    path: gitops/overlays/production
    
  destination:
    server: https://kubernetes.default.svc
    namespace: spot-production
    
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    
  revisionHistoryLimit: 10
